apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: utcdate-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: utcdate-service
    spec:
      containers:
      - name: utcdate-service
        image: duyushui/utc-date-service:latest
        ports:
        - containerPort: 3001

apiVersion: v1
kind: Service
metadata: 
   name: utcdata-service
spec:
   ports:
   - port: 80
     targetPort: 8080
   selector:
     app: aggregator-service
   type: NodePort
