apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: utcdate-service
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: utcdate-service
    spec:
      containers:
      - name: utcdate-service
        image: duyushui/utc-date-service:latest
        ports:
        - containerPort: 3001

